version: '3'
services:
  fastapi:
    restart: always
    env_file: .env
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/app
    links:
      - db

  db:
      image: mysql:5.7
      ports:
        - "33000:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
