var crime_types = [
  'Arson',
'Assault Offenses',
'Bribery',
'Burglary/Breaking and Entering',
'Counterfeiting/Forgery',
'Destruction/Damage/Vandalism of Property',
'Drug/Narcotic Offenses',
'Embezzlement',
'Extortion/Blackmail',
'Fraud Offenses',
'Gambling Offenses',
'Homicide Offenses',
'Kidnaping/Abduction',
'Larceny/Theft Offenses',
'Motor Vehicle Thef',
'Pornography/Obscene Material',
'Prostitution Offenses',
'Robbery',
'Sex Offenses, Forcible',
'Sex Offenses, Nonforcible',
'Stolen Property Offenses (Receiving, etc.)',
'Weapon Law Violations',
'Bad Checks',
'Curfew/Loitering/Vagrancy Violations',
'Disorderly Conduct',
'Driving Under the Influence',
'Drunkenness',
'Family Offenses, Nonviolent',
'Liquor Law Violations',
'Peeping Tom',
'Runaway',
'Trespass of Real Property',
'All Other Offenses',
'Unknown'
]